# Generated by Django 4.1.7 on 2023-02-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="skills",
            field=models.CharField(default="", max_length=255),
        ),
    ]
